ffi-cdecl/ffi-cdecl.lua, ffi-cdecl/test/sample.cpp, ffi-cdecl/test/util.c
w/ GCC 5 support.
The cdecl files have once again to be changed, it's part of my WIP base PR.
=> Update GCC-LUA & co

nightswatcher/Makefile, nightswatcher/nightswatcher.py
gitlab has updated its nightly build output URL.
=> Update gitlab URL of nightly build

nightswatcher/Makefile, nightswatcher/nightswatcher.py
References https://github.com/koreader/koreader/pull/3723
=> nightswatcher: update regex to include date

nightswatcher/Makefile, nightswatcher/nightswatcher.py
Cf. https://github.com/koreader/koreader/pull/4256
=> nightswatcher: add Android and PRSTUX to OTA models

nightswatcher/Makefile, nightswatcher/nightswatcher.py
Also download AppImage artifact. Fixes #22.
=> [chore] nightswatcher: don't duplicate OTA targz

nightswatcher/Makefile, nightswatcher/nightswatcher.py
Also add self-documenting named groups to the regular expression.
=> nightswatcher: stable handling & android-x86 OTA

nightswatcher/Dockerfile, nightswatcher/Makefile, nightswatcher/nightswatcher.py
Server support for <https://github.com/koreader/koreader/pull/4620>.
=> [feat] nightswatcher: full download version check

nightswatcher/Makefile, nightswatcher/nightswatcher.py
See https://github.com/koreader/koreader-misc/pull/30/files#r264063375
=> [fix] nightswatcher: remove -latest- file before copy

nightswatcher/Makefile, nightswatcher/nightswatcher.py
Cf. https://github.com/koreader/koreader/pull/4869
=> [feat] nightswatcher: add android-fdroid-latest

nightswatcher/Makefile, nightswatcher/nightswatcher.py
Cf. <https://github.com/koreader/koreader/issues/5355#issuecomment-529874084>.
=> [fix] Android ARM OTA name

nightswatcher/Dockerfile, nightswatcher/Makefile, nightswatcher/nightswatcher.py, nightswatcher/requirements.txt
Also bump some depencencies.
https://github.com/patrickfav/uber-apk-signer/releases/tag/v1.1.0
See https://github.com/koreader/koreader/pull/5828 https://github.com/koreader/koreader/pull/5697 https://github.com/koreader/virdevenv/pull/47
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-misc/38)
=> nightswatcher: add remarkable to OTA

README.md
Pinging @NiLuJe
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-misc/39)
=> Basic release guidelines

nightswatcher/Makefile, nightswatcher/nightswatcher.py
References https://github.com/koreader/koreader/issues/9632
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-misc/44)
=> nightswatcher: add aarch64 to architectures

nightswatcher/Dockerfile, nightswatcher/Makefile, nightswatcher/nightswatcher.py, nightswatcher/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-misc/49)
=> nightswatcher: update dependencies, add -C to zsyncmake

nightswatcher/nightswatcher.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-misc/53)
=> nightswatcher: implement some minor suggestions from Pylint and Pylance

nightswatcher/nightswatcher.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-misc/55)
=> nightswatcher: add kindlehf build

nightswatcher/Dockerfile, nightswatcher/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-misc/57)
=> nightswatcher: update to phusion/baseimage:noble-1.0.0

nightswatcher/nightswatcher.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-misc/62)
=> nightswatcher: drop old TODO (no longer applicable)

nightswatcher/nightswatcher.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-misc/64)
=> nightswatcher: minor factorization

nightswatcher/nightswatcher.py
To make it easier to handle new file formats.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-misc/65)
=> nightswatcher: minor change
